### ISSUE TITLE
Problem installing vue-native init project-name --no-crna

### ISSUE THREAD

**Issue by IsraelDCastro** [GeekyAnts/vue-native-website#25]
When I tried to run the code, It gave me this error

```
Creating_ react native app vueNative project
Create react-native vueNative project
/usr/local/lib/node_modules/vue-native-cli/src/index.js:140
  process.chdir(projectName);
          ^

Error: ENOENT: no such file or directory, chdir 'vueNative'
    at handleAndAddVueNativePackageDependencySync (/usr/local/lib/node_modules/vue-native-cli/src/index.js:140:11)
    at createNormalNativeApp (/usr/local/lib/node_modules/vue-native-cli/src/index.js:90:3)
    at init (/usr/local/lib/node_modules/vue-native-cli/src/index.js:78:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/vue-native-cli/src/index.js:59:7)
    at Command.listener (/usr/local/lib/node_modules/vue-native-cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/vue-native-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/vue-native-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/vue-native-cli/src/index.js:63:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```

**Comment by neeraj-singh47** [comment]
@IsraelDCastro Can you specify the vue-native-cli version? Check if you are using the latest version of vue-native-cli

**Comment by IsraelDCastro** [comment]
@neeraj-singh47 vue-native-cli@0.0.3, i installed as the docs said

**Comment by neeraj-singh47** [comment]
@IsraelDCastro Is it working without `--no-crna` option?

**Comment by IsraelDCastro** [comment]
@neeraj-singh47 Yes, without `--no-crna` it works good, I could install the project using `vue-native init`

**Comment by neeraj-singh47** [comment]
@IsraelDCastro Can you try again with some different name. Seems to be working fine

**Comment by IsraelDCastro** [comment]
@neeraj-singh47 I tried, it continues with the same problem

**Comment by neeraj-singh47** [comment]
@IsraelDCastro Try updating react-native-cli as well

**Comment by OzanKurt** [comment]
That also doesn't work. @neeraj-singh47
