### ISSUE TITLE
cannot init new project

### ISSUE THREAD

**Issue by knot22** [GeekyAnts/vue-native-website#53]
Following the instructions on [this page](https://vue-native.io/docs/installation.html) to create a new project using the `vue-native init <projectName>` command, the new project was not created.  This was attempted on a Windows 10 machine which has Expo CLI and Vue Native CLI installed.  Below is what was entered in the Git Bash terminal along with the result.  The new project was to be named `helloWorld` but nothing was created in the destination folder.  What needs to be changed for the project to be created?
````
jason.black@MARIGOLD MINGW64 /z/files/development/vue_native/code/sandbox
$ vue-native init helloWorld
Using globally installed expo-cli 3.7.1

Creating Vue Native project helloWorld

- Creating project with expo-cli

[18:28:18] --name: argument is required in non-interactive mode.
√ Created project with expo-cli

(node:14736) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chdir 'Z:\files\development\vue_native\code\sandbox' -> 'helloWorld'
    at process.chdir (internal/process/main_thread_only.js:29:13)
    at installPackages (C:\Users\jason.black\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:182:11)
    at createExpoProject (C:\Users\jason.black\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:123:3)
    at init (C:\Users\jason.black\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:101:5)
    at Command.<anonymous> (C:\Users\jason.black\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:69:7)
    at Command.listener (C:\Users\jason.black\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (C:\Users\jason.black\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\jason.black\AppData\Roaming\npm\node_modules\vue-native-cli\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\jason.black\AppData\Roaming\npm\node_modules\vue-native-cli\src\index.js:81:9)
(node:14736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by knot22** [comment]
I have switched to using Ubuntu 18.04 on a VM so this issue is no longer a concern.
